language: python
python:
  - "3.7"
install:
  - make compile
jobs:
  include:
    - stage: test
      script: make test
    - stage: image
      if: branch = master
      script: make image
    - stage: image push
      if: branch = master
      script: make imagePush
