TMP_DIR?=/tmp/pointillism_prs
FILE?=test/fixtures/tg.repos

daily: search

search:
	python3 -m prmonster.github

leads:
	wc -l github.leads.sorted
	@grep DISCOVERED logs/github_search.log >> github.leads
	@cat github.leads | sort | uniq > github.leads.sorted
	@rm github.leads
	@cp github.leads.sorted github.leads
	wc -l github.leads.sorted

leadsList:
	cut -f2 github.leads.sorted | sort | uniq

clean:
	rm -rf $(TMP_DIR)

run: clean
	python3 -m prmonster $(FILE)


