version: 2.1
jobs:
  build:
    docker:
      - image: tgrayson/build
    steps:
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "0c:aa:9c:05:11:c3:80:28:b0:67:f9:f2:f8:80:16:96"
      - checkout
      - run:
          name: compile
          command: make compile
      - run:
          name: test
          command: make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  image:
    docker:
      - image: tgrayson/build
    steps:
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "0c:aa:9c:05:11:c3:80:28:b0:67:f9:f2:f8:80:16:96"
      - checkout
      - run:
          name: build image
          command: make image
      - run:
          name: push image
          command: make imagePush
  deploy:
    docker:
      - image: tgrayson/build
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0c:aa:9c:05:11:c3:80:28:b0:67:f9:f2:f8:80:16:96"
            - "56:99:68:c1:e2:41:98:28:87:51:a4:fb:ad:ba:5d:ac"
            - "SHA256:BvIjOPnp5LiRHFaP/mnnS4F8oJa5qlNS0x7wQf799PU"
      - checkout
      - run:
          name: deploy staging
          command: make deploy DEPLOY_HOST=staging.pointillism.io
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - image:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - image
      - deploy staging:
          type: approval
          requires:
            - test
            - build image
            - push image
      - staging deploy:
          requires:
            - deploy staging
      - deploy prod:
          type: approval
          requires:
            - test
            - build image
            - push image
      - prod deploy:
          requires:
            - deploy prod
