version: 2.1
jobs:
  build:
    docker:
      - image: tgrayson/build
    steps:
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "0c:aa:9c:05:11:c3:80:28:b0:67:f9:f2:f8:80:16:96"
      - checkout
      - run:
          name: compile
          command: make compile
      - run:
          name: test
          command: make test
      - store_test_results:
          path: test-results/result.xml
      - run:
          name: build image
          command: make image
      - run:
          name: push image
          command: make imagePush

